services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    network_mode: "host"
    user: ${USER_ID}:${GROUP_ID}
    environment:
      DISPLAY: $DISPLAY
      CARGO_TARGET_DIR: /tmp/target
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: .
        target: /app
    working_dir: /app